### ISSUE TITLE
Different colors for letters in text

### ISSUE THREAD

**Issue by YaCubeK** [aagarwal1012/Animated-Text-Kit#152]
I wanted to make my letters in text when I use TypewriterAnimatedTextKit with different colors, but dont know how to do it. Usually I used RichText to achieve this effect, but with your package I cannot find property to define colors for letters because there was used List<String> text and I cannot asign RichText with TextSpan in it to my page. If it is possible can you implement this feature, also if it is present can you tell me how I can achieve it?

**Comment by awhitford** [comment]
This is definitely not possible with the current code.  As you said, a text string is supplied -- not a child widget.

Rather than hard-coding the _String->Text_, maybe we could generalize that to be _String->Widget_ -- then you could supply your own function to do whatever you want...  I'd need to double check the code to see if its truly that easy.

**Comment by YaCubeK** [comment]
Ok, sir. Thank you for your reply, I will wait for your response.

**Comment by awhitford** [comment]
This request inspired PR #157.  I ended up refactoring the library to make adding additional animations easier.  This PR still needs to be approved, merged, and released.  However, with it, you can achieve your animation goal...

First, create a unique Animated Text class which contains your logic.  You can clone `TypewriterAnimatedText` and tweak it, like:
```dart
class ColoredTypewriterAnimatedText extends AnimatedText {
  // The text length is padded to cause extra cursor blinking after typing.
  static const extraLengthForBlinks = 8;

  /// The [Duration] of the delay between the apparition of each characters
  ///
  /// By default it is set to 30 milliseconds.
  final Duration speed;

  /// Define unique colors for characters.
  final Map<String, Color> charColors;

  ColoredTypewriterAnimatedText(
    String text, {
    TextAlign textAlign = TextAlign.start,
    @required TextStyle textStyle,
    this.speed = const Duration(milliseconds: 30),
    @required this.charColors,
  })  : assert(null != speed),
        super(
          text: text,
          textAlign: textAlign,
          textStyle: textStyle,
          duration: speed * (text.characters.length + extraLengthForBlinks),
        );

  Animation<int> _typewriterText;

  @override
  Duration get remaining =>
      speed *
      (textCharacters.length + extraLengthForBlinks - _typewriterText.value);

  @override
  void initAnimation(AnimationController controller) {
    _typewriterText = StepTween(
      begin: 0,
      end: textCharacters.length + extraLengthForBlinks,
    ).animate(controller);
  }

  Iterable<TextSpan> colorizeText(String text) =>
      text.characters.map((_) => TextSpan(
            text: _,
            style: textStyle.copyWith(color: charColors[_]),
          ));

  @override
  Widget completeText() => RichText(
        text: TextSpan(
          children: [
            ...colorizeText(text),
            TextSpan(
              text: '_',
              style: textStyle.copyWith(color: Colors.transparent),
            )
          ],
          style: textStyle,
        ),
        textAlign: textAlign,
      );

  /// Widget showing partial text
  @override
  Widget animatedBuilder(BuildContext context, Widget child) {
    final textLen = textCharacters.length;
    final typewriterValue = _typewriterText.value;

    var visibleString = text;
    var suffixColor = Colors.transparent;
    if (typewriterValue == 0) {
      visibleString = '';
    } else if (typewriterValue > textLen) {
      suffixColor = (typewriterValue - textLen) % 2 == 0
          ? textStyle.color
          : Colors.transparent;
    } else {
      visibleString = textCharacters.take(typewriterValue).toString();
      suffixColor = textStyle.color;
    }

    return RichText(
      text: TextSpan(
        children: [
          ...colorizeText(visibleString),
          TextSpan(
            text: '_',
            style: textStyle.copyWith(color: suffixColor),
          )
        ],
        style: textStyle,
      ),
      textAlign: textAlign,
    );
  }
}
```
(Extending `TypewriterAnimatedText` could save some code.  However, it doesn't give you access to `_typewriterText` because Dart has no concept of _protected_ class variables across files.  As a result, I chose to just clone the class.)

The above code basically adds a `charColors` map where you can customize colors, and then the `colorizeText` method translates a text String to a bunch of `TextSpan` that can be fed to the `RichText` widget.

Then, you can use it like:
```dart
      child: AnimatedTextKit(
        onTap: () {
          print('Tap Event');
        },
        animatedTexts: [
          ColoredTypewriterAnimatedText(
            'Hello World!',
            textStyle: const TextStyle(fontSize: 30.0, fontFamily: 'Agne'),
            charColors: const {'e': Colors.blue, 'o': Colors.red},
          ),
          ColoredTypewriterAnimatedText(
            'Issue 152',
            textStyle: const TextStyle(fontSize: 30.0, fontFamily: 'Agne'),
            charColors: const {'e': Colors.blue},
          ),
        ],
      ),
```

This sample code can be further optimized.  However, it does work, and it illustrates how you could create custom animations fairly easily.

Hope this helps!

**Comment by YaCubeK** [comment]
When I tried to copy first code with the ColoredTypewriterAnimatedText by creating a new file, it showed an error that AnimatedText class is not exist. Am I putting first code right? What I tried is just create file in my project and put it there. What I should do?

**Comment by awhitford** [comment]
> PR #157 still needs to be approved, merged, and released. However, with it, you can achieve your animation goal...

The PR was merged 🎉 , but not yet released.

**Comment by YaCubeK** [comment]
Thanks lot!

**Comment by awhitford** [comment]
Version 3 has been released.
