### ISSUE TITLE
Add Duration of displayed text after animate in, before animate out

### ISSUE THREAD

**Issue by xj42** [aagarwal1012/Animated-Text-Kit#190]
The total length of the fade in / out anumations is controllable, but the length of time the text is shown before fading out is not configurable. It would be very useful to be able to specify the animate in / out durations seperate from the duration between those animations.

**Comment by ritvij14** [comment]
Hi, I would like to contribute to this issue as a part of GSSOC '21. This is the first time I am contributing to a flutter package so could someone guide me a little as to how should I proceed with this issue?

**Comment by awhitford** [comment]
To clarify, you can presently specify the _total duration_ of the _Fade In and Out_.  The _Fade In, Pause, and Fade Out_ are hard-coded ratios:
* Fade In - between 0 and 50% (or 0.5)
* Pause - between 50% and 80% (0.5 and 0.8)
* Fade Out - between 80% to 100% (0.8 to 1.0)

Lines 27 and 34 have the magic numbers:
https://github.com/aagarwal1012/Animated-Text-Kit/blob/e5c3b8471a83eba1677447754e9ec9f563c77f6b/lib/src/fade.dart#L22-L37

So rather than introducing new durations, you just need to offer the flexibility to override the `fadeInEnd` (0.5) and the `fadeOutBegin` (0.8).

**Comment by ritvij14** [comment]
@awhitford thanks for the explanation, I have looked at the code of this file and now have an idea of what to do.

Just one doubt though, how should I test my changes and check if they work correctly or not?

**Comment by awhitford** [comment]
@ritvij14 Excellent question!

We measure [test coverage](https://codecov.io/gh/aagarwal1012/Animated-Text-Kit), and likely the existing tests would provide adequate _coverage_.  We strive for 90% or better, but don't want to see it below 80%.

The project has an `example` project that may be used to manually test functionality.  (This code is also executed as part of the automated test.)

Overall, testing animations leaves a lot to be desired...  We do not have tests that validate animation frame details.  This could be an area of research & development.  See the existing [test code](https://github.com/aagarwal1012/Animated-Text-Kit/blob/master/test/smoke_test.dart) to see what is currently being done.

Hope this helps!
