### ISSUE TITLE
Text is truncated in LiquidFill on tablets

### ISSUE THREAD

**Issue by Dumdidoo** [aagarwal1012/Animated-Text-Kit#233]
I'm using LiquidFill in a Scaffold Appbar.  It works fine in phones (Nexus 4, 3, Pixel 3, 4, 4XL, Samsung Note 10+, Pixel 3XL).

However, on tablets, the text is truncated - it replaces the second half of the text with an ellipsis... .  This is true in a Pixel C tablet AVD API 30, and in a physical Samsung Galaxy T580 running Android 8.1.0.

(Animated-Text-Kit ^4.1.1)

**Comment by awhitford** [comment]
I think AppBars in Flutter are intentionally using `overflow: TextOverflow.ellipsis` for the `title` to keep the text to one line.  That isn't being specified by the _Animated Text Kit_ code.

I am surprised to read that it works for phones and not tablets because I would think that tablets have more room. 🤔 

You might try wrapping the `TextLiquidFill` with a [DefaultTextStyle](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html) that specifies the default `overflow`.  I'm not sure which [overflow value](https://api.flutter.dev/flutter/rendering/TextOverflow-class.html) would make sense, but not `ellipsis`.  The [code](https://github.com/aagarwal1012/Animated-Text-Kit/blob/1d31bece67d365239d6759cf8f24658d18fd82d6/lib/src/text_liquid_fill.dart#L158) simply is using a `Text` widget:

https://github.com/aagarwal1012/Animated-Text-Kit/blob/1d31bece67d365239d6759cf8f24658d18fd82d6/lib/src/text_liquid_fill.dart#L158-L163

**Comment by Dumdidoo** [comment]
Hi, thanks for your comment. I've investigated it further, and it seems to be just a problem with the fontsize scaling that I was using. The scaling wasn't handling the much bigger size of the tablet width - it worked on all the smaller phones. So, mea culpa, my mistake, I think it's fine now. Please close this issue, and thanks for your help.
