### ISSUE TITLE
issue with pixels in case text is big

### ISSUE THREAD

**Issue by kw2019ltd** [aagarwal1012/Animated-Text-Kit#87]
even if FadeAnimatedTextKit inside expanded widget still getting below error

![image](https://user-images.githubusercontent.com/47334522/83400827-38ef6f80-a40c-11ea-9017-0317ab393fb9.png)

**Comment by AadumKhor** [comment]
Hi @kw2019ltd. Please provide the full source code so that I can replicate this behavior.

**Comment by kw2019ltd** [comment]
its easy make Text with font size big enough you will got this error

**Comment by AadumKhor** [comment]
I have tried these. Have a look at the screenshots. 

1. Simple `Row` as `Scaffold` body with `FadeAnimatedTextKit` in `Expanded`

```
    return Scaffold(
        body: Row(children: [
          Expanded(
            child: FadeAnimatedTextKit(
              text: [
                'REmaindasgfhasdlkfasdfanssdfadsdasdfadfa',
                'ladsjfhasdjfhaslkdjfasndfkjansdblfkjaasdfasdf',
                'adsjfgalkdsjfhaslkdjfhasdlkjfhadjkfbasdfasdfa'
              ],
              isRepeatingAnimation: true,
              repeatForever: true,
              textStyle: TextStyle(
                  color: Colors.black,
                  fontSize: 100.0,
                  fontWeight: FontWeight.bold),
            ),
          )
        ]));
```
![image](https://user-images.githubusercontent.com/37381075/83610089-ab8f5500-a59c-11ea-8d67-d8e3dfc66ad0.png)

2. Column with Expanded

```
    return Scaffold(
        body: Column(children: [
      Expanded(
        child: FadeAnimatedTextKit(
          text: [
            'REmaindasgfhasdlkfasdfanssdfadsdasdfadfa',
            'ladsjfhasdjfhaslkdjfasndfkjansdblfkjaasdfasdf',
            'adsjfgalkdsjfhaslkdjfhasdlkjfhadjkfbasdfasdfa'
          ],
          isRepeatingAnimation: true,
          duration: Duration(milliseconds: 2000),
          repeatForever: true,
          textStyle: TextStyle(
              color: Colors.black,
              fontSize: 100.0,
              fontWeight: FontWeight.bold),
        ),
      )
    ]));
```
![image](https://user-images.githubusercontent.com/37381075/83609708-4471a080-a59c-11ea-996d-08acb76f67ee.png)

There is no overflow in both cases. I also added spacing between letters randomly, expanded works as it is. This is why I was asking for the source code since there might be an issue with your code or there might even be a very specific use case where this happens. Again I would ask you to share the source code for me to replicate this.
